local KeyboardLayout = dofile("plugins/externalkeyboard.koplugin/keyboard_layout.lua")

describe("ExternalKeyboard layout resolver (us)", function()
    local function r(name, shift)
        return KeyboardLayout.resolve("us", name, { Shift = shift or false })
    end

    it("case-folds letters", function()
        assert.are.equal("a", r("A"))
        assert.are.equal("A", r("A", true))
        assert.are.equal("z", r("Z"))
        assert.are.equal("Z", r("Z", true))
    end)

    it("passes digits through and maps shifted digits to symbols", function()
        assert.are.equal("1", r("1"))
        assert.are.equal("!", r("1", true))
        assert.are.equal("@", r("2", true))
        assert.are.equal(")", r("0", true))
    end)

    it("maps base and shifted punctuation", function()
        assert.are.equal(";", r(";"))
        assert.are.equal(":", r(";", true))
        assert.are.equal("/", r("/"))
        assert.are.equal("?", r("/", true))
        assert.are.equal("-", r("-"))
        assert.are.equal("_", r("-", true))
        assert.are.equal("[", r("["))
        assert.are.equal("{", r("[", true))
        assert.are.equal("`", r("`"))
        assert.are.equal("~", r("`", true))
        assert.are.equal('"', r("'", true))
    end)

    it("resolves space at both levels", function()
        assert.are.equal(" ", r(" "))
        assert.are.equal(" ", r(" ", true))
    end)

    it("uses an AltGr level when a layout defines one", function()
        assert.is_nil(KeyboardLayout.resolve("us", "1", { AltGr = true }))
        assert.is_nil(KeyboardLayout.resolve("us", "1", { Shift = true, AltGr = true }))
    end)

    it("returns nil for keys it does not handle", function()
        assert.is_nil(r("F1"))
        assert.is_nil(r("Home"))
        assert.is_nil(r("Up"))
    end)

    it("returns nil for an unknown layout", function()
        assert.is_nil(KeyboardLayout.resolve("dvorak", "1", { Shift = true }))
    end)

    it("returns nil while a non-Shift modifier is held", function()
        assert.is_nil(KeyboardLayout.resolve("us", "U", { Ctrl = true }))
        assert.is_nil(KeyboardLayout.resolve("us", "A", { Alt = true }))
        assert.is_nil(KeyboardLayout.resolve("us", "C", { Meta = true }))
        assert.is_nil(KeyboardLayout.resolve("us", "1", { Ctrl = true, Shift = true }))
    end)
end)
